document.body.style.backgroundColor = "pink";
var name = prompt("Enter Name");
document.write(name);
document.body.style.backgroundColor = "pink";
// document.body.style.backgroundColor="gray";
document.body.style.fontSize="50px";
document.body.style.textAlign="center";
document.body.style.paddingTop="50px";
document.body.style.color="green";
document.body.style.fontStyle="arial";
